on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: step
      run: echo hello
    - name: checkout
      uses: actions/checkout@v4
    - name: setup
      run: make setup
    - name: build
      run: make build
    - name: Install Viam CLI
      run: |        
          sudo curl -o viam.exe "https://storage.googleapis.com/packages.viam.com/apps/viam-cli/viam-cli-latest-windows-amd64.exe"
    - name: Publish build to Viam registry
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: |           
          viam login api-key --key-id ${{ secrets.viam_key_id }} --key ${{ secrets.viam_key_value }}
          viam module upload --platform windows/amd64 --version 0.0.3 --upload dist/archive.tar.gz                                

