on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: step
      run: echo hello
    - name: checkout
      uses: actions/checkout@v4
    - name: setup
      run: make setup
    - name: build
      run: make build
